CREATE TABLE IF NOT EXISTS "Comments"
(
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    "ArticleId" integer NOT NULL,

    "Author" varchar(200) NOT NULL,

    "Content" text NOT NULL,

    "CreatedAt" timestamp with time zone NOT NULL,

    "UpdatedAt" timestamp with time zone NULL
);

CREATE INDEX IF NOT EXISTS "IX_Comments_ArticleId"
    ON "Comments" ("ArticleId");