CREATE TABLE IF NOT EXISTS "Profanity"
(
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Word" varchar(50) NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_Profanity_Word"
    ON "Profanity" ("Word");

INSERT INTO "Profanity" ("Word")
VALUES
    ('fuck'),
    ('shit'),
    ('bitch'),
    ('asshole')
ON CONFLICT DO NOTHING;