CREATE TABLE IF NOT EXISTS "ProfanityWords"
(
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    "Word" varchar(200) NOT NULL,
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_ProfanityWords_Word"
    ON "ProfanityWords" (LOWER("Word"));